
# React Native Colo Loco autolinks native files colocated next to your JS files
# More info here: https://github.com/jamonholmgren/react-native-colo-loco

# require_relative '../node_modules/react-native-colo-loco/scripts/ios.rb'
# link_colocated_native_files(app_name: 'Fotos', app_path: "../app")


require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
require File.join(File.dirname(`node --print "require.resolve('react-native/package.json')"`), "scripts/react_native_pods")
require File.join(File.dirname(`node --print "require.resolve('@react-native-community/cli-platform-ios/package.json')"`), "native_modules")

platform :ios, '12.0'


require 'json'
podfile_properties = JSON.parse(File.read('./Podfile.properties.json')) rescue {}

target 'fotos' do
  permissions_path = '../node_modules/react-native-permissions/ios'
  use_expo_modules!
  pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary"
  post_integrate do |installer|
    begin
      expo_patch_react_imports!(installer)
    rescue => e
      Pod::UI.warn e
    end
  end
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => podfile_properties['expo.jsEngine'] == 'hermes'
  )

  pod 'RNSharedElement', :path => '../node_modules/react-native-shared-element'

  target 'fotosTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!()

  post_install do |installer|
    flipper_post_install(installer)
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end
