/// <reference types="react" />
export declare const PlayIcon: () => JSX.Element;
export declare const PauseIcon: () => JSX.Element;
export declare const Spinner: () => JSX.Element;
export declare const FullscreenEnterIcon: () => JSX.Element;
export declare const FullscreenExitIcon: () => JSX.Element;
export declare const ReplayIcon: () => JSX.Element;
export declare const MuteIcon: () => JSX.Element;
export declare const UnmuteIcon: () => JSX.Element;
