
// This file is autogenerated from a react-native-colo-loco script.
// Please do not edit it directly.
package com.photos;

import com.facebook.react.bridge.NativeModule;
import com.facebook.react.bridge.ReactApplicationContext;
import com.facebook.react.uimanager.ViewManager;

import java.util.ArrayList;
import java.util.List;

import android.util.Log;

class ColoLoco {
  // Any colocated modules are added here (except ViewManagers)
  public static List<NativeModule> colocatedModules(ReactApplicationContext reactContext) {
    List<NativeModule> modules = new ArrayList<>();
    // This list is auto-generated. Do not edit manually.



    return modules;
  }

  // Any colocated ViewManagers are added here
  public static List<ViewManager> colocatedViewManagers(ReactApplicationContext reactContext) {
    List<ViewManager> viewManagers = new ArrayList<>();
    // This list is auto-generated. Do not edit manually.



    return viewManagers;
  }
}
  